CVE-2023-41036
Macvim is a text editor for MacOS. 
Prior to version 178, Macvim makes use of an insecure interprocess communication (IPC) mechanism which could lead to a privilege escalation. 
Distributed objects are a concept introduced by Apple which allow one program to vend an interface to another program. 
What is not made clear in the documentation is that this service can vend this interface to any other program on the machine. 
The impact of exploitation is a privilege escalation to root - this is likely to affect anyone who is not careful about the software they download and use MacVim to edit files that would require root privileges. 
Version 178 contains a fix for this issue.

Traducción:
Macvim es un editor de texto para MacOS.
Antes de la versión 178, Mavim hacía uso de un mecanismo del interproceso de comunicación inseguro (IPC) el cual podía derivar a una escalada de privilegios.
Objetos distribuidos son un concepto introducido por Apple el cual permite vender esta interfaz a cualquier otro programa en la máquina. 
El impacto de explotación es una escalada de privilegios a la raíz - esto pudiendo afectar a cualquiera que no sea cuidadoso acerca del software que descarga y usa MacVim para editar sus ficheros que puedan requerir permisos de administrador.
La versió 178 contiene un arreglo para este problema.

References
ORIGIN: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-41036
MISC:https://github.com/macvim-dev/macvim/blob/d9de087dddadbfd82fcb5dc9734380a2f829bd0a/src/MacVim/MMAppController.h#L28
URL:https://github.com/macvim-dev/macvim/blob/d9de087dddadbfd82fcb5dc9734380a2f829bd0a/src/MacVim/MMAppController.h#L28
MISC:https://github.com/macvim-dev/macvim/commit/399b43e9e1dbf656a1780e87344f4d3c875e4cda
URL:https://github.com/macvim-dev/macvim/commit/399b43e9e1dbf656a1780e87344f4d3c875e4cda
MISC:https://github.com/macvim-dev/macvim/security/advisories/GHSA-9jgj-jfwg-99fv
URL:https://github.com/macvim-dev/macvim/security/advisories/GHSA-9jgj-jfwg-99fv
MISC:ttps://github.com/macvim-dev/macvim/blob/d9de087dddadbfd82fcb5dc9734380a2f829bd0a/src/MacVim/MMBackend.h
URL:ttps://github.com/macvim-dev/macvim/blob/d9de087dddadbfd82fcb5dc9734380a2f829bd0a/src/MacVim/MMBackend.h

CVE-2023-40024
ScanCode.io is a server to script and automate software composition analysis pipelines. 
In the `/license/` endpoint, the detailed view key is not properly validated and sanitized, which can result in a potential cross-site scripting (XSS) vulnerability when attempting to access a detailed license view that does not exist.
Attackers can exploit this vulnerability to inject malicious scripts into the response generated by the `license_details_view` function. 
When unsuspecting users visit the page, their browsers will execute the injected scripts, leading to unauthorized actions, session hijacking, or stealing sensitive information. 
This issue has been addressed in release `32.5.2`. Users are advised to upgrade. 
There are no known workarounds for this vulnerability.

Traducción
ScanCode.io es un servidor para hacer scripts y componer software automático, además de analizar tuberías.
En el `/license/` endpoint, la tecla de vista detallada no está propiamente validada y sin limpiar, el cual puede resultar en una vulnerabilidad de código de cross-site (XSS) cuando se intenta acceder a la vista detallada de licencia que no existe.
Atacantes pueden explotar esta vulnerabilidad para inyectar código malicioso en la respuesta generada por la función `license_details_view`
Cuando los usuarios sin conocimiento visitan la página, los buscadores ejecutarán los códigos inyectados, dando lugar a acciones sin autorizar, sesiones robadas, o robo de información importante.
Este problema se ha visto en el lanzamiento `32.5.2.`. Los usuarios es recomendado que actualicen.
No hay arreglos conocidos para esta vulnerabilidad.

References
ORIGIN: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-40024
MISC:https://github.com/nexB/scancode.io/blob/dd7769fbc97c84545579cebf1dc4838214098a11/CHANGELOG.rst#v3252-2023-08-14
URL:https://github.com/nexB/scancode.io/blob/dd7769fbc97c84545579cebf1dc4838214098a11/CHANGELOG.rst#v3252-2023-08-14
MISC:https://github.com/nexB/scancode.io/security/advisories/GHSA-6xcx-gx7r-rccj
URL:https://github.com/nexB/scancode.io/security/advisories/GHSA-6xcx-gx7r-rccj

## CVE-2021-40729
### Descripción
Adobe Acrobat Reader DC versión 21.007.20095, 21.007.20096, 20.004.30015, y 17.011.30202 están afectados por 
una vulnerabilidad de lectura fuera de límites que podría conducir a la divulgación de memoria sensible. 
Un atacante podría aprovechar esta vulnerabilidad para eludir mitigaciones como ASLR. La explotación de 
este problema requiere la interacción del usuario, ya que la víctima debe abrir un archivo PDF malicioso

### Referencias
[MISC](https://helpx.adobe.com/security/products/acrobat/apsb21-104.html)
[URL](https://helpx.adobe.com/security/products/acrobat/apsb21-104.html)

### Impacto

### Explotación

### Solución


## CVE-2023-5357
### Descripción
El plugin Instagram for WordPress para WordPress es vulnerable a Stored Cross-Site Scripting a través de 
shortcodes en versiones hasta, e incluyendo, 2.1.6 debido a insuficiente sanitización de entrada y escape
de salida en atributos suministrados por el usuario. Esto hace posible que atacantes autenticados con
permisos de nivel de colaborador y superiores, inyecten scripts web arbitrarios en páginas que se ejecutarán
cada vez que un usuario acceda a una página inyectada.

## Referencias
[MISC](https://plugins.trac.wordpress.org/browser/instagram-for-wordpress/tags/2.1.6/templates/instagramPost.php#L12)
[URL](https://plugins.trac.wordpress.org/browser/instagram-for-wordpress/tags/2.1.6/templates/instagramPost.php#L12)
[MISC](https://www.wordfence.com/threat-intel/vulnerabilities/id/3991d8d0-57a8-42e7-a53c-97508f7e137f?source=cve)
[URL](https://www.wordfence.com/threat-intel/vulnerabilities/id/3991d8d0-57a8-42e7-a53c-97508f7e137f?source=cve)

### Impacto

### Explotación

### Solución
